export const keys = [
    { label: "C", key: "q" },
    { label: "C#", key: "2", isBlack: true },
    { label: "D", key: "w" },
    { label: "D#", key: "3", isBlack: true },
    { label: "E", key: "e" },
    { label: "F", key: "r" },
    { label: "F#", key: "5", isBlack: true },
    { label: "G", key: "t" },
    { label: "G#", key: "6", isBlack: true },
    { label: "A", key: "y" },
    { label: "A#", key: "7", isBlack: true },
    { label: "B", key: "u" },
    { label: "C", key: "i" },
    { label: "C#", key: "9", isBlack: true },
    { label: "D", key: "o" },
    { label: "D#", key: "0", isBlack: true },
    { label: "E", key: "p" },
    { label: "F", key: "z" },
    { label: "F#", key: "s", isBlack: true },
    { label: "G", key: "x" },
    { label: "G#", key: "d", isBlack: true },
    { label: "A", key: "c" },
    { label: "A#", key: "f", isBlack: true },
    { label: "B", key: "v" },
    { label: "C", key: "b" },
    { label: "C#", key: "h", isBlack: true },
    { label: "D", key: "n" },
    { label: "D#", key: "j", isBlack: true },
    { label: "E", key: "m" },
    { label: "F", key: "," },
    { label: "F#", key: "l", isBlack: true },
    { label: "G", key: ".", mappedKey: "dot" },
    { label: "G#", key: ";", isBlack: true },
    { label: "A", key: "/", mappedKey: "slash" },
    { label: "A#", key: "'", isBlack: true },
    { label: "", key: "" },
];
